/* ROOMS ACTIONS */

export const CONNECTION = 'CONNECTION';

export const DISCONNECT = 'DISCONNECT';

export const CREATE_ROOM = 'CREATE_ROOM';

export const ROOM_CREATED = 'ROOM_CREATED';

export const CONNECT_TO_ROOM = 'CONNECT_TO_ROOM';

export const ROOM_CONNECTED = 'ROOM_CONNECTED';

export const ROOM_IS_FULL = 'ROOM_IS_FULL';

export const ROOM_DOESNT_EXIST = 'ROOM_DOESNT_EXIST';

export const OPPONENT_CAME_OUT = 'OPPONENT_CAME_OUT';


/*  GAME ACTIONS */

export const CHOSE_GESTURE = 'CHOSE_GESTURE';

export const RESULT_OF_ROUND = 'RESULT_OF_ROUND';

export const START_GAME = 'START_GAME';

export const START_NEW_ROUND = 'START_NEW_ROUND';

export const PLAYER_LEAVE = 'PLAYER_LEAVE';

/*  CHAT ACTIONS */

export const RECEIVE_MESSAGE ='RECEIVE_MESSAGE';

export const SEND_MESSAGE ='SEND_MESSAGE';